tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface": "#131313",
                "on-error-container": "#ffdad6",
                "surface-container-lowest": "#0e0e0e",
                "secondary": "#c7c6c6",
                "on-secondary": "#2f3131",
                "on-primary-container": "#005721",
                "background": "#131313",
                "on-tertiary-fixed-variant": "#474746",
                "inverse-on-surface": "#313030",
                "spotify-green-dark": "#1DB954",
                "error-container": "#93000a",
                "inverse-surface": "#e5e2e1",
                "on-tertiary": "#313030",
                "surface-container-low": "#1c1b1b",
                "tertiary-container": "#bdbbba",
                "outline-variant": "#3c4a3c",
                "on-primary-fixed": "#002108",
                "tertiary": "#d9d7d6",
                "on-primary-fixed-variant": "#00531f",
                "on-surface": "#e5e2e1",
                "inverse-primary": "#006e2c",
                "surface-tint": "#34e36a",
                "surface-container-highest": "#353534",
                "surface-variant": "#353534",
                "secondary-fixed-dim": "#c7c6c6",
                "secondary-container": "#484949",
                "primary-container": "#1ed760",
                "gradient-male-end": "#3D1533",
                "on-secondary-fixed": "#1a1c1c",
                "primary-fixed-dim": "#34e36a",
                "tertiary-fixed": "#e5e2e1",
                "surface-bright": "#393939",
                "on-background": "#e5e2e1",
                "on-secondary-container": "#b8b8b8",
                "gradient-female-end": "#0F1F33",
                "primary-fixed": "#69ff89",
                "error": "#ffb4ab",
                "surface-container-high": "#2a2a2a",
                "primary": "#4cf479",
                "surface-container": "#201f1f",
                "track-amber-end": "#BF360C",
                "pure-white": "#FFFFFF",
                "tertiary-fixed-dim": "#c8c6c5",
                "surface-dim": "#131313",
                "on-secondary-fixed-variant": "#464747",
                "on-tertiary-container": "#4b4b4b",
                "gradient-male-start": "#7A2E6E",
                "secondary-fixed": "#e3e2e2",
                "on-primary": "#003913",
                "on-surface-variant": "#bbcbb8",
                "on-tertiary-fixed": "#1c1b1b",
                "on-error": "#690005",
                "outline": "#859583",
                "gradient-female-start": "#1B3A5C",
                "track-amber-start": "#FF8F00"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px",
                "2xl": "1.5rem"
            },
            spacing: {
                "container-margin": "20px",
                "card-padding": "24px",
                "gutter": "16px",
                "section-gap": "48px",
                "base": "8px"
            },
            fontFamily: {
                "countdown-num": ["Montserrat"],
                "headline-xl": ["Montserrat"],
                "label-caps": ["Montserrat"],
                "headline-lg-mobile": ["Montserrat"],
                "headline-lg": ["Montserrat"],
                "body-md": ["Montserrat"],
                "player-track": ["Montserrat"]
            },
            fontSize: {
                "countdown-num": ["28px", { "lineHeight": "1.1", "fontWeight": "700" }],
                "headline-xl": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
                "label-caps": ["11px", { "lineHeight": "1.2", "letterSpacing": "0.15em", "fontWeight": "700" }],
                "headline-lg-mobile": ["22px", { "lineHeight": "1.3", "fontWeight": "700" }],
                "headline-lg": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
                "body-md": ["14px", { "lineHeight": "1.6", "fontWeight": "400" }],
                "player-track": ["16px", { "lineHeight": "1.4", "fontWeight": "700" }]
            }
        }
    }
}
